apiVersion: apps/v1
kind: Deployment
metadata:
  name: merhaba-dunya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api-node
        image: burakkutluk/rest-api
        ports:
        - containerPort: 3000
